sudo: required
dist: trusty

language: node_js

node_js:
    - "node"

before_install:
    - sudo apt-get update
    - sudo apt-get -y install build-essential
    - sudo apt-get -y install git
    - sudo apt-get -y install python3-pygments
    - sudo apt-get -y install ruby
    - sudo apt-get -y install wget
    - sudo apt-get -y install yui-compressor

install:
    - mkdir work
    - wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}-64bit.deb -O $PWD/work/hugo.deb
    - sudo dpkg -i $PWD/work/hugo.deb
    - npm install npm -g
    - npm install bower -g
    #- npm insatll html-proofer -g
    #- npm insatll html-minifier -g
script:
    - hugo version 
    - hugo
