sudo: required
dist: trusty
branches:
  only:
  - master
  - stable
language: node_js
node_js:
- node
before_install:
#- sudo apt-get update
#- sudo apt-get -y install build-essential
#- sudo apt-get -y install git
- sudo apt-get -y install python3-pygments
- sudo apt-get -y install ruby
#- sudo apt-get -y install wget
install:
- mkdir work
- wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}-64bit.deb
  -O $PWD/work/hugo.deb
- sudo dpkg -i $PWD/work/hugo.deb
- npm install
#- git clone git://github.com/kangax/html-minifier.git $PWD/work/minifier/
#- npm link $PWD/work/minifier/
script:
- grunt deploy
#- hugo
#- html-minifier --collapse-whitespace --file-ext html --input-dir ./public --output-dir ./public
after_success:
#- ls -al ./public 
#- git remote add origin https://${GH_REF}
#- git config user.name ${Git_User_Name}
#- git config user.email ${Git_User_Email}
#- git add .
#- git commit -m "[ci skip] deploy from ysqi"
#- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" origin gh-pages
#- sudo sh ./scripts/deploy.sh

env:
  global:
  - REPO="github.com/ysqi/travis-broken-example.git"
  - USER="ysqi"
  - EMAIL="devysq@gmail.com"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="gh-pages"