sudo: required
dist: trusty

# safelist
branches:
  only:
  - master
  - stable

language: node_js

node_js:
    - "node"

before_install:
    - sudo apt-get update
    - sudo apt-get -y install build-essential
    - sudo apt-get -y install git
    - sudo apt-get -y install python3-pygments
    - sudo apt-get -y install ruby
    - sudo apt-get -y install wget
    #- sudo apt-get -y install yui-compressor

install:
    - mkdir work
    - wget https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}-64bit.deb -O $PWD/work/hugo.deb
    - sudo dpkg -i $PWD/work/hugo.deb
    - git clone git://github.com/kangax/html-minifier.git $PWD/work/minifier/
    - npm link $PWD/work/minifier/ 
    #- npm install -g grunt-cli
    #- npm install npm -g
    #- npm install bower -g
    #- npm insatll html-proofer -g
    #- npm insatll html-minifier -g
script:
    - hugo version 
    - hugo
after_script: 
    - html-minifier --collapse-whitespace --file-ext html --input-dir ./ --output-dir ./
    - cd ./public
    - git init
    - git config user.name ${Git_User_Name} 
    - git config user.email ${Git_User_Email}
    - git add .
    - git commit -m "[ci skip] deploy from ysqi"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages

env:
   - GH_REF="github.com/ysqi/travis-broken-example" 
   - Git_User_Name="ysqi"
   - Git_User_Email="devysq@gmail.com"